Add CONFIG_TARGET_NVIDIA_GB200NVL for platform identification
At DGXOPENBMC-13091, there's requirement that need to identify the
platform to  have different behavior with diffeernt hardware.

This is an example change for those people who need to identify the
platform to have different behavior by adding board(same SOC) config
in U-boot via kconfig.

Test: bitbake -c compile u-boot-aspeed-sdk and have compilation error
 with
 #ifdef CONFIG_TARGET_NVIDIA_GB200NVL
 #error "CONFIG_TARGET_NVIDIA_GB200NVL is defined"
 #endif
 | u-boot-aspeed-sdk/arch/arm/mach-aspeed/cpuinfo.c:14:10:
 | error: #error "CONFIG_TARGET_NVIDIA_GB200NVL is defined"
 |    14 |         #error "CONFIG_TARGET_NVIDIA_GB200NVL is defined"
 |       |          ^~~~~

Fixes jira https://jirasw.nvidia.com/browse/DGXOPENBMC-13091
Signed-off-by: Iris Chen <irchen@nvidia.com>