Add CONFIG_GB200NVL for platform identification
At DGXOPENBMC-13091, there's requirement that need to identify the
platform to  have different behavior with diffeernt hardware.

This is an example for people who need to identify the
platform to have different behavior in U-boot via kconfig.

Test: bitbake -c compile u-boot-aspeed-sdk and have compilation error
 with
 #ifdef CONFIG_GB200NVL
 #error "CONFIG_GB200NVL is defined"
 #endif
 | u-boot-aspeed-sdk/arch/arm/mach-aspeed/cpuinfo.c:14:10:
 | error: #error "CONFIG_GB200NVL is defined"
 |    14 |         #error "CONFIG_GB200NVL is defined"
 |       |          ^~~~~

    Fixes jira https://jirasw.nvidia.com/browse/DGXOPENBMC-13091
Signed-off-by: Iris Chen <irchen@nvidia.com>