Add Kbuild and base board c file to fix compile error
Test: bitbake -c compile u-boot-aspeed-sdk have compilation error
 with
 #ifdef CONFIG_TARGET_NVIDIA_GB200NVL
 #error "CONFIG_TARGET_NVIDIA_GB200NVL is defined"
 #endif
 | u-boot-aspeed-sdk/board/nvidia/gb200nvl/gb200nvl.c:3:10:
 | error: #error "CONFIG_TARGET_NVIDIA_GB200NVL is defined"
 |    14 |         #error "CONFIG_TARGET_NVIDIA_GB200NVL is defined"
 |       |          ^~~~~
And compile u-boot successfully without #error

Fixes jira https://jirasw.nvidia.com/browse/DGXOPENBMC-13091
Signed-off-by: Iris Chen <irchen@nvidia.com>